### ISSUE TITLE
got error?

### ISSUE THREAD

**Issue by InfiBatnis** [jlreymendez/greedy-merchants-ecs#1]
![issue 2](https://user-images.githubusercontent.com/66300225/92892035-fdbcfd80-f44a-11ea-8ddb-15fbc026c29c.png)
![issue 1](https://user-images.githubusercontent.com/66300225/92892047-001f5780-f44b-11ea-87ce-b9365f2f134e.png)

**Comment by jlreymendez** [comment]
Strange, I am not getting this error and in fact this repo has Svelto added inside the assets folder, so it wouldn't be on the package manager. However I did notice that the manifest.json has entries for Svelto.Common and Svelto.Tasks, so I can see how this could be creating some issues. I will remove the manifest.json entries for now, since Svelto.ECS 3.0 isn't on open-upm yet. Thanks for reporting this.

**Comment by jlreymendez** [comment]
Let me know if last push didn't fixed things for you.
